### ISSUE TITLE
Add linewidth parameter to plot method

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/samila#101]
#### Description
It seems that this parameter has a significant effect on the output

## Linewidth: 1.2 | Spot Size: 0.1
![l12_s01](https://user-images.githubusercontent.com/7515099/154801642-c38af7f5-a712-4fd9-9c57-405ab0b26087.png)

## Linewidth: 1.2 | Spot Size: 10
![112_s10](https://user-images.githubusercontent.com/7515099/154801674-a59c3741-c597-4d99-856a-88f885dcfa5b.png)

## Linewidth: 12 | Spot Size: 0.1
![l120_s01](https://user-images.githubusercontent.com/7515099/154801679-8981271d-7afc-49ce-9f47-4154fa571bdf.png)

## Linewidth: 12 | Spot Size: 10
![1120_s10](https://user-images.githubusercontent.com/7515099/154801697-4e2734ec-ec1b-450f-b585-ca45ac16ac3d.png)

**Comment by evanofslack** [comment]
I can implement this feature, feel free to assign the issue to me @sepandhaghighi

**Comment by sepandhaghighi** [comment]
@evanofslack Hi
Why not? Assigned to you 🚀

**Comment by evanofslack** [comment]
Hi @sepandhaghighi,

This is implemented. Waiting for 0.5 release before PR to dev.
