### ISSUE TITLE
How do you define the S1 space

### ISSUE THREAD

**Issue by CesarSGZ** [sepandhaghighi/samila#107]
I understand that in the example you provide, x and y are defined between -pi and +pi. However, how do you define this space so the image will be generated between this numbers? I think I need a deeper explanation of how the parameters in the functions work to generate the transformation.

**Comment by sadrasabouri** [comment]
The S1 space is the **input space** which is generated like this (from [here](https://github.com/sepandhaghighi/samila/blob/master/samila/genimage.py#L82)):
```
range_prod = list(itertools.product(range1, range2))
```
And the S2 space is the space where the Samila art (generated image) is in it. `function1` and `function2` are the functions that do this transformation.

**Comment by sadrasabouri** [comment]
@CesarSGZ If the concept is OK now you can close this issue otherwise we'll close it on our next version release.

**You can ask these questions (which is not an issue related to the package itself) in discord.**
