### ISSUE TITLE
Make samila available to download with conda

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/samila#137]
#### Description
Make samila available to download with conda

**Comment by jtpio** [comment]
FYI @sepandhaghighi I just opened the following PR to make `samila` available on conda-forge: https://github.com/conda-forge/staged-recipes/pull/20098

Still a draft for now. Looks like [art](https://pypi.org/project/art/) would also need to be packaged for conda: https://pypi.org/project/art/

Would it be ok to add you as a maintainer there? Thanks!

**Comment by sepandhaghighi** [comment]
> FYI @sepandhaghighi I just opened the following PR to make `samila` available on conda-forge: [conda-forge/staged-recipes#20098](https://github.com/conda-forge/staged-recipes/pull/20098)
> 
> Still a draft for now. Looks like [art](https://pypi.org/project/art/) would also need to be packaged for conda: https://pypi.org/project/art/

Hi @jtpio 
Thanks 💯 🚀 
art is available on my [personal channel](https://anaconda.org/sepandhaghighi/art). But this will be exceptional if it is also available in **conda-forge**.
I have a question about version updating in **conda-forge**. Will this update be manual or automatic? (for example from samila **v0.8** to samila **v0.9**)

> Would it be ok to add you as a maintainer there? Thanks!

Why not? Add me!

SH

**Comment by jtpio** [comment]
> art is available on my [personal channel](https://anaconda.org/sepandhaghighi/art). But this will be exceptional if it is also available in **conda-forge**.

Looks like there is an open PR for this package already: https://github.com/conda-forge/staged-recipes/pull/18698
It seems to have stalled, but we could revive it.



> I have a question about version updating in **conda-forge**. Will this update be manual or automatic? (for example from samila **v0.8** to samila **v0.9**)

Yes the conda-forge bot automatically opens PRs when new releases are published to PyPI and pings the maintainers for review. It's also possible to setup auto merging to publish the release on conda-forge faster.
