### ISSUE TITLE
`rotate` function optimization

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/samila#185]
#### Description
It seems that some parts of this function are redundant

**Comment by sadrasabouri** [comment]
This is what happened when we move the code below after rotation. (all extra information like axis, markers and etc are presented)
So I think we'd need this part anyway thus **no optimization is possible**. If you think so, we can close this issue.
```python
ax.set_axis_off()
ax.patch.set_zorder(-1)
ax.add_artist(ax.patch)
```
![test-45](https://user-images.githubusercontent.com/43045767/229314062-751b5b0b-c253-4b9b-9fb0-ea74c47b41f0.png)
